<?php

namespace anvildev\simpleform\web\assets\cp;

use craft\web\AssetBundle;
use craft\web\assets\cp\CpAsset;
use craft\web\View;

/**
 * Control-panel CSS/JS for Simple Form's CP screens (forms index + builder,
 * submissions index + detail, per-form integrations, spam settings).
 *
 * Consolidates what used to be per-template inline <style>/<script> blocks
 * (#100) into one versioned, cache-bustable bundle. Both files are written to
 * be inert when their target elements are absent, so the bundle is safe to
 * register on any CP screen. Craft publishes the dist/ directory to
 * cpresources with a content hash.
 */
class SimpleFormCpAsset extends AssetBundle
{
    public function init(): void
    {
        $this->sourcePath = __DIR__ . '/dist';

        $this->depends = [CpAsset::class];

        $this->css = ['css/cp.css'];
        $this->js = ['js/cp.js', 'js/form-builder.js'];

        parent::init();
    }

    /**
     * Ships the 'simple-form' translation catalog to the client so the
     * hand-authored form builder (form-builder.js) can localize its UI labels
     * via Craft.t('simple-form', ...) (#335). The list mirrors exactly the
     * strings wrapped in t() in form-builder.js; keep the two in sync.
     */
    public function registerAssetFiles($view): void
    {
        parent::registerAssetFiles($view);

        if (!$view instanceof View) {
            return;
        }

        $view->registerTranslations('simple-form', [
            'Text',
            'Email',
            'URL',
            'Textarea',
            'Select',
            'Checkbox',
            'Radio',
            'Date',
            'Time',
            'Date & Time',
            'Number',
            'Phone',
            'File Upload',
            'Name',
            'Address',
            'Payment',
            'Hidden',
            'Agree / Consent',
            'Rating',
            'Opinion Scale',
            'Signature',
            'Entries',
            'Categories',
            'Tags',
            'Users',
            'Assets',
            'Calculation',
            'Repeater',
            'Heading',
            'Section Divider',
            'HTML Block',
            'Callout',
            'Prefix',
            'First name',
            'Middle name',
            'Last name',
            'Suffix',
            'Address line 1',
            'Address line 2',
            'City',
            'State / Region',
            'Postal code',
            'Country',
            'Option 1',
            'I agree to the [privacy policy](https://example.com/privacy)',
            'Item',
            'Step {n}',
            '(numbered {n} — steps renumber contiguously on the form)',
            'Hidden — captured silently; never shown on the form.',
            'Move up',
            'Move down',
            'Remove',
            '(heading)',
            '— divider —',
            'HTML block',
            '(text)',
            '(callout)',
            '(untitled)',
            'Field',
            '{label} field added.',
            'Delete the “{name}” field?',
            '{count} other field has rules based on it ({names}); those rules will be removed too.',
            '{count} other fields have rules based on it ({names}); those rules will be removed too.',
            'Moved to position {pos} of {total}.',
            'Field removed.',
            '{type} field',
            'Done',
            'Label',
            'Handle',
            'Required field',
            'Help Text',
            'Error Message',
            'Leave blank to use the default',
            'Shown for this site when the field fails validation. Leave blank to use the default (translated) message.',
            'Default value',
            'Prefilled when the form first loads. For choice fields, use the option value. A visitor’s input overrides it.',
            'Hidden — captured silently. This field is never shown on the form; the label is used only for the CP submission view and exports.',
            'Step / Page',
            'Row',
            'Drag a field onto the left or right edge of another to place them side by side (up to {max} columns), or set a matching Row number here.',
            'Prefill from query string',
            'Use form default',
            'On',
            'Off',
            'When enabled, this field is pre-filled from a URL query parameter. Prefilled values are still validated on submit.',
            'Query parameter',
            'field handle',
            'The URL query parameter to read. Leave blank to use the field handle.',
            'Heading Level',
            'Heading 2',
            'Heading 3',
            'Heading 4',
            'Heading Text',
            'Label (optional)',
            'Optional text shown over the divider line. Leave blank for a plain rule.',
            'HTML / Twig',
            'Rendered safely on the form: Twig runs in a sandbox and the output is purified — scripts, inline handlers and unsafe URLs are stripped.',
            'Static paragraph copy shown between fields. Plain text only — line breaks are preserved and any markup is escaped (use the HTML Block for real formatting).',
            'Tone',
            'Info',
            'Success',
            'Warning',
            'Error',
            'Icon (optional)',
            'An optional glyph or emoji shown before the text (e.g. ℹ️, ⚠️). Leave blank for none.',
            'Guidance copy shown in a toned panel between fields. Plain text only — line breaks are preserved and any markup is escaped (use the HTML Block for real formatting).',
            'Minimum Length',
            'Maximum Length',
            'Minimum Value',
            'Maximum Value',
            'Placeholder',
            'Show Country Selector',
            'Default Country',
            'Allowed Countries',
            'Leave all unchecked to allow every country.',
            'Minimum Digits',
            'Maximum Digits',
            'Custom Pattern',
            'Optional regex applied to the number’s digits. Leave blank for the default check.',
            'Date Format',
            '(first available)',
            'Asset Volume',
            'Allowed Extensions',
            'Max Size (MB)',
            'Allow Multiple Files',
            'Pen Color',
            'Pad Background',
            'Amount Type',
            'Fixed amount',
            'From a field',
            'Fixed Amount',
            'Min Amount',
            'Max Amount',
            'Amount Field Handle',
            'Currency',
            'Allow Coupons',
            'Consent Text',
            'Add link',
            '[privacy policy](https://example.com/privacy)',
            'Use [label](https://…) for a single inline link. Per-site translatable.',
            'Required Message',
            'You must agree before submitting.',
            'Maximum (1–10)',
            'Icon Style',
            'Stars',
            'Hearts',
            'Numbers',
            'Minimum',
            'Maximum',
            'Left Label',
            'Right Label',
            'Formula',
            'Reference fields by handle, e.g. {quantity} * {unitPrice}. Allowed: + - * / ( ) and min, max, round, ceil, floor, abs.',
            'Insert Field',
            'Decimal Places',
            'Thousands Separator',
            'Minimum Rows',
            'Maximum Rows (0 = unlimited)',
            'Add Button Label',
            'Add another',
            'Enable Autocomplete',
            'Allowed Sources',
            'Leave all unchecked to allow any source of this element type.',
            'No sources available for this element type.',
            'Allow Multiple',
            'Limit',
            'Source',
            'Static value',
            'URL query parameter',
            'Logged-in user',
            'Cookie',
            'Query Parameter',
            'User Attribute',
            'User ID',
            'Username',
            'Cookie Name',
            'Value',
            'Default Value',
            'Inner Fields',
            'The sub-fields a visitor fills in per row. Allowed types: text, email, number, select.',
            'required',
            'Min',
            'Max',
            'Add Inner Field',
            'Add Option',
            'Sub-fields',
            'Sub-field Labels (this site)',
            'Required',
            'Equal',
            'Wide',
            'Wider',
            'Widest',
            '{label} ({n}×)',
            'Column Width',
            'Relative width within the row. This row: {ratio}.',
            'Options',
            'Option Labels (this site)',
            'Translate each option for this site. Leave blank to use the source label. Option values are managed on the primary site.',
            'Correct',
            'Pts',
            'Points',
            'is',
            'is not',
            'is empty',
            'is not empty',
            'contains',
            'greater than',
            'less than',
            '— field —',
            '— value —',
            'Remove rule',
            'Match',
            'all',
            'any',
            'of:',
            'Add rule',
            'Conditions',
            'Add another field first to base conditions on it.',
            'Enable conditional logic',
            'Show',
            'Hide',
            'this field when',
            'Make this field required when…',
            '— jump to —',
            'Remove jump',
            'Logic jumps',
            'Add a field after this one to jump to it.',
            'When this field’s answer matches, skip ahead to the chosen field’s step. First matching rule wins.',
            'Add jump',
            'Field "{name}": label is required.',
            'Field "{name}": handle is required.',
            'Field "{name}": invalid handle.',
            'Duplicate handle "{handle}".',
            'Field "{name}": needs at least one option.',
            'Field "{name}": needs at least one inner field.',
            'Field "{name}": minimum rows cannot exceed maximum rows.',
            'Field "{name}": inner field "{iname}" has an invalid handle.',
            'Field "{name}": duplicate inner handle "{handle}".',
            'Field "{name}": inner field "{iname}" has an unsupported type.',
            'Field "{name}": inner select "{iname}" needs at least one option.',
            'Message {n}',
            'Remove message',
            'Show this message when',
            'A rule references a field that no longer exists: {fields}.',
            'Message',
        ]);
    }
}
